name: "0-Container Deployment Pipeline"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  username: ${{ secrets.AWS_USERNAME }}
  password: ${{ secrets.AWS_PASSWORD }}
  # github.repository as <account>/<repo>
  #REPO_NAME: 04_05_CI_CD_Container_AWS_App_Runner
  IMAGE_NAME: ${{ github.repository }}
  #IMAGE_NAME: 04-05-ci-cd-container-aws-app-runner

jobs:
  integration:
    uses: ./.github/workflows/integrate-python-app.yml
    with:
      environment: Production
    permissions:
      contents: read
      packages: read

  delivery:
    needs: [integration]
    uses: ./.github/workflows/deliver-container-image.yml
    
    permissions:
      contents: read
      packages: write
      id-token: write

  deploy-staging:
    needs: [delivery]
    uses: ./.github/workflows/deploy-aws-app-runner.yml
    with:
      environment: Staging
    permissions:
      packages: read
    secrets: inherit

  deploy-production:
    needs: [deploy-staging]
    uses: ./.github/workflows/deploy-aws-app-runner.yml
    with:
      environment: Production
    permissions:
      packages: read
    secrets: inherit
